package buisness.models;

public class User {
    public String login;
    public Integer id;
    public String avatarUrl;
    public String gravatarId;
    public String url;
    public String htmlUrl;
    public String followersUrl;
    public String followingUrl;
    public String gistsUrl;
    public String starredUrl;
    public String subscriptionsUrl;
    public String organizationsUrl;
    public String reposUrl;
    public String eventsUrl;
    public String receivedEventsUrl;
    public String type;
    public Boolean siteAdmin;
    public Object name;
    public Object company;
    public Object blog;
    public Object location;
    public Object email;
    public Object hireable;
    public Object bio;
    public Integer publicRepos;
    public Integer publicGists;
    public Integer followers;
    public Integer following;
    public String createdAt;
    public String updatedAt;
    public Integer privateGists;
    public Integer totalPrivateRepos;
    public Integer ownedPrivateRepos;
    public Integer diskUsage;
    public Integer collaborators;
    public Plan plan;
}